### ISSUE TITLE
Live doesn't work.

### ISSUE THREAD

**Issue by derand** [cdown/yturl#35]
How about live videos?

```
Traceback (most recent call last):
  File "../../venv/bin/yturl", line 11, in <module>
    load_entry_point('yturl==2.0.2', 'console_scripts', 'yturl')()
  File "/Users/maliy/work/tests/venv/lib/python3.7/site-packages/yturl.py", line 147, in main
    itag_to_url_map = itags_for_video(args.video_id)
  File "/Users/maliy/work/tests/venv/lib/python3.7/site-packages/yturl.py", line 80, in itags_for_video
    streams = api_response['url_encoded_fmt_stream_map'].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```

**Comment by cdown** [comment]
Yeah, live uses RTMP, which isn't supported. We should put some better message in this case though.
