### ISSUE TITLE
Getting a YouTubeAPIError with any URL, including the example URL

### ISSUE THREAD

**Issue by danperks** [cdown/yturl#37]
The title explains it all. Other URLs don't work too.

```console
C:\Users\xxxx>yturl 'http://www.youtube.com/watch?v=8TCxE0bWQeQ'
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38-32\Scripts\yturl-script.py", line 11, in <module>
    load_entry_point('yturl==2.0.2', 'console_scripts', 'yturl')()
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\yturl.py", line 147, in main
    itag_to_url_map = itags_for_video(args.video_id)
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\yturl.py", line 76, in itags_for_video
    raise YouTubeAPIError(reason)
yturl.YouTubeAPIError: Invalid parameters.
```

**Comment by cdown** [comment]
I'm afraid the title really doesn't explain it all, since it works just fine locally and externally for me with that URI :-)

- What version of yturl are you using?
- What does running with `--debug` output, in its entirety?

**Comment by cdown** [comment]
Closing without prejudice due to lack of response.
