### ISSUE TITLE
Error when running yturl

### ISSUE THREAD

**Issue by Fraer** [cdown/yturl#43]
I've installed from github as specified in the README.

```
yturl 'https://www.youtube.com/watch?v=xiX9YQ0Dem0'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/yturl", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yturl.py", line 152, in main
    itag_to_url_map = itags_for_video(args.video_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yturl.py", line 81, in itags_for_video
    ) from None
NotImplementedError: Live and streaming videos are unsupported.
```

**Comment by izaac** [comment]
Same here using `pip install -U git+https://github.com/cdown/yturl.git@develop`

**Comment by yashasolutions** [comment]
same
